services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"

  event-service:
    image: eclipse-temurin:21-jdk
    container_name: event-service
    working_dir: /app
    volumes:
      - ../event-service/build/libs:/app
    command: java -jar event-service-0.0.1-SNAPSHOT.jar
    depends_on:
      - kafka
      - mongo
    ports:
      - "8081:8081"

  shadow-ledger-service:
    image: eclipse-temurin:21-jdk
    container_name: shadow-ledger-service
    working_dir: /app
    volumes:
      - ../shadow-ledger-service/build/libs:/app
    command: java -jar shadow-ledger-service-0.0.1-SNAPSHOT.jar
    depends_on:
      - kafka
      - mongo
    ports:
      - "8082:8082"

  drift-correction-service:
    image: eclipse-temurin:21-jdk
    container_name: drift-correction-service
    working_dir: /app
    volumes:
      - ../drift/build/libs:/app
    command: java -jar drift-0.0.1-SNAPSHOT.jar
    depends_on:
      - kafka
      - mongo
